name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest

        with:
          # GitHub account
          user: raaz-srijan

          # Generated file
          filename: metrics.svg

          # Token
          token: ${{ secrets.METRICS_TOKEN }}

          # Theme
          template: classic

          # Core information
          base: header, activity, community, repositories, metadata

          # Timezone
          config_timezone: Asia/Kathmandu

          # Display
          config_display: large

          # Most used programming languages
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_sections: most-used
          plugin_languages_details: percentage

          # Recent GitHub activity
          plugin_activity: yes
          plugin_activity_limit: 5

          # Repository information
          plugin_repositories: yes
          plugin_repositories_featured: ""

          # Contribution calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
